let palabras = {
    Yo:"I",
    tú_usted_ustedes_vosotros_vosotras:"you",
    nosotros_nosotras:"we",
    ellos_ellas:"they",
    él:"he",
    ella:"she",
    pronombre_para_objetos:"it",
    ser_estar:"to be",
    0:"zero",
    1:"one",
    2:"two",
    3:"three",
    4:"four",
    5:"five",
    6:"six",
    7:"seven",
    8:"eight",
    9:"nine",
    10:"ten",
    11:"eleven",
    12:"twelve",
    13:"thirteen",
    14:"fourteen",
    15:"fifteen",
    16:"sixteen",
    17:"seventeen",
    18:"eighteen",
    19:"nineteen",
    20:"twenty",
    21:"twenty_one",
    25:"twenty_five",
    29:"twenty_nine",
    30:"thirty",
    32:"thirty_two",
    40:"forty",
    50:"fifty",
    60:"sixty",
    70:"seventy",
    80:"eighty",
    90:"ninety",
    99:"ninety nine",
    100:"one hundred",
    frase:"oración_sentence",
    verbo:"verb",
    sustantivo:"noun",
    pronombre:"pronoun",
    lunes:"Monday",
    martes:"Tuesday",
    miércoles:"Wednesday",
    jueves:"Thursday",
    viernes:"Friday",
    sábado:"Saturday",
    domingo:"Sunday",
    a_day:"un_día", 
    una_semana:"a_week",
    un_mes:"a_month",
    un_año:"a year",
    un_diario:"a_diary",
    una_billetera:"a wallet",
    un_paraguas:"an umbrella",
    una_tarjetade_identidad:"an ID",
    un_reloj:"a watch",
    a_camera:"una cámara",
    un_móvil_un_celular:"a cell phone",
    una_pila_batería: "a battery",
    una_botella_de_agua :"a bottle of water",
    un_mapa :"a map",
    una_bolsa:"	a bag",
    una_bicicleta:"a bicycle",
    bicileta:"bike",
    un_libro:"a book",
    una_moneda:"a coin",
    una_tarjetade_crédito:"a credit card",
    un_diccionario:"a dictionary",
    un_archivo:"a file",
    una_carpeta:"a folder",
    lentes_gafas:"glasses",
    llaves:"keys",
    lápiz_labial: "lipstick",
    una_revista:"a magazine",
    un_periódico:"a newspaper",
    un_bolígrafo:"a pen",
    un_lápiz:"a pencil",
    una_foto:"a photo",
    cocinar:"to cook",
    beber_agua:"to drink water",
    manejar_un_coche:"to drive a car",
    almorzar:"to have lunch",
    almorzar:"to eat lunch",
    ir_al_cine:"go to the cinema",
    dinero:"money",
    gustar:"like",
    escuchar_música:"to listen to music",
    vivir_en_una_casa:"to live in a house",
    tocar_la_guitarra:"to play the guitar",
    leer_un_libro:"to read a book",
    estudiar:"to study",
    hablar_inglés:"to speak English",
    ver_la_tele:"to watch TV",    
    trabajar_en_una_oficina:"to work in an office",
    hacer_los_deberes:"to do homework",
    jugar_béisbol:"to play baseball",
    un_trabajo:"a job",
    un_médico:"a doctor",
    un_músico:"a musician",
    un_ingeniero:"an engineer",
    un_dependiente:"a shop assistant",
    un_limpiador:"a cleaner",
    un_oficial_de_policía:"a police officer",
    un_mesero:" camarero a waiter",
    una_mesera:" camarera a waitress",
    un_contable:"an accountant",
    un_actor:"an actor",
    una_actriz:"an actress",
    un_constructor:"a builder",
    un_profesor:"a teacher",
    un_manager:"a manager",
    una_ama_de_casa:"a housewife",
    un_abogado:"a lawyer",
    desempleado:"unemployed",
    jubilado:"retired",
    peluquero:"a hairdresser",
    un_periodista:"a journalist",
    una_enfermera:"a nurse",
    un_piloto:"a pilot",
    un_político:"a politician",
    una_secretaria:"a secretary",
    un_estudiante:"a student",
    negro:"black",
    azul:"blue",
    marrón:"brown",
    verde:"green",
    gris:"grey",
    naranja:"orange",
    rosa:"pink",
    rojo:"red",
    blanco:"white",
    amarillo:"yellow",
    malo:"bad",
 }

